##############################
###        WINDOWS         ###
##############################

# Startup setup
windowrule = match:initial_title Steam, workspace 10 silent
windowrule = match:initial_class vesktop, workspace 9 silent

# Move games to dedicated spaces
windowrulev2 = tile, class:pobfrontend

windowrulev2 = tile, initialClass:^drivethrurpg
windowrulev2 = workspace emptym+1, initialClass:^drivethrurpg

windowrule {
  name=Games
  match:tag = game

  no_anim = on
  monitor = DP-2
  workspace = emptym+1
  maximize = on
}

windowrule = match:class factorio, tag +game
windowrule = match:class Hollow Knight Silksong, tag +game
windowrule = match:initial_class steam_app_230410 , tag +game
windowrule = match:initial_title Soulframe, tag +game
windowrule = match:initial_title World of Warcraft, tag +game

windowrule {
  name=Path of Exile
  match:tag = poe

  fullscreen = on
  monitor = DP-2
  workspace = 12
}

windowrule = match:title (Path of Exile), tag +poe
windowrule = match:class (steam_app_238960), tag +poe

windowrule {
  name=PoE Overlay
  match:tag = poe_overlay

  monitor = DP-2
  workspace = 12
  float = on
  no_blur = on
  no_shadow = on
  no_focus = on
  pin = on
  render_unfocused = on
  size = monitor_w monitor_h
  center = on
}

windowrule = match:initial_title (Awakened PoE Trade), tag +poe_overlay

# Misc pop-ups
windowrule {
  name = Pop up windows
  match:tag = pop_up

  float = on
  center = on
}

windowrule {
  name = rofi
  match:class = ^rofi

  tag = +pop_up
  no_anim = on
}

windowrule {
  name = Color Picker
  match:title = Color Picker

  tag = +pop_up
  stay_focused = on
}

windowrule {
  name = Diablo 2
  match:title = Diablo II

  tag = +pop_up
  suppress_event = activate activatefocus
  monitor = DP-2
}

windowrule = match:initial_class org.kde.kcalc, tag +pop_up
windowrule = match:initial_class ^xdg-desktop-portal-gtk, tag +pop_up
windowrule = match:initial_class ^org.freedesktop.impl.portal.desktop.kde, tag +pop_up
windowrule = match:initial_class zenity, tag +pop_up
windowrule = match:initial_class Bitwarden, tag +pop_up
windowrule = match:initial_class org.inkscape.Inkscape, match:title ^[^-]+$, tag +pop_up

windowrulev2 = tag +popup, class:Vampire Survivors
windowrulev2 = tag +popup, initialClass:naps2, initialTitle:^DCP-1510 \(brother4)
windowrulev2 = tag +popup, class:qimgv, title:^Edit shortcut
